frr defaults traditional
hostname bgp-tor
log stdout informational
!
router bgp 64513
 bgp router-id 192.168.111.1
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor CLUSTER peer-group
 neighbor CLUSTER remote-as 64512
 bgp listen range 192.168.111.0/24 peer-group CLUSTER
 !
 address-family ipv4 unicast
  neighbor CLUSTER activate
 exit-address-family
!
